### ISSUE TITLE
According to the HyperKYC team, this SDK supports Swift versions from 5.5 onwards. However, it cannot be installed on iOS with the current Swift version being 5.9.2.

### ISSUE THREAD

**Issue by hagridleitc** [hyperverge/HyperKYC#99]
Failed to build module 'HyperKYC'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)', while this compiler is 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)'). Please select a toolchain which matches the SDK.

**Comment by NeelkanthTandel** [comment]
same issue
@hagridleitc did you find any solution?

**Comment by koinbxrahul** [comment]
I am also facing same issue any solution in swiftui project ?

**Comment by buivanhieu-bstar** [comment]
me too, did all of you find any solution?

**Comment by hagridleitc** [comment]
sorry I don't remember, let contact HPV customer support. They will support.
